### ISSUE TITLE
Question about compile

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/universe-viewer#1]
I wanted to ask how to compile it on Ubuntu? For Windows.

**Comment by CaseyraeStarfinder** [comment]
Greetings,

This unfortunately is not possible.  You can build the viewer for Linux distributions on Ubuntu, Windows distributions on Windows, and Mac distributions on Mac OS.  Unfortunately you can not build the viewer on one operating system for all operating system types because they all have their own dependency requirements.

You can however use VMWare Player which you can get for free at http://www.vmware.com and during install and initial run you can select the non commercial option which will make it free.  In Vmware player it is possible to set up virtual machines for Windows and Mac however which most developers usually do in order to develop software and test on all three operating system types.  

Note: The viewer code in this repository is now out of date as we are currently working on the new version of the viewer and hope to have it released very soon.  

Caseyrae Starfinder
Core Developer
Viewer Development
Work Group leader
Viewer Development Work Group
Second Galaxy Development Team
